import type {
  IdeologyLevel,
  IdeologyNode,
  IdeologyNodePlacement,
  IdeologyRegistryEntry,
  IdeologyRelation,
  IdeologyRelationType,
} from "./types";

const relation = (type: IdeologyRelationType, targetId: string, note: string): IdeologyRelation => ({ type, targetId, note });

const node = (
  id: string,
  label: string,
  level: IdeologyLevel,
  summary: string,
  sourceRefs: readonly string[],
  options: Readonly<{
    anchorId?: string;
    aliases?: readonly string[];
    canonicalParentId?: string;
    confidence?: IdeologyNode["confidence"];
    placement?: IdeologyNodePlacement;
    relations?: readonly IdeologyRelation[];
  }> = {},
): IdeologyNode => ({
  id,
  label,
  level,
  summary,
  canonicalParentId: options.canonicalParentId,
  anchorId: options.anchorId,
  placement: options.placement ?? "canonical",
  status: options.anchorId && (options.placement ?? "canonical") === "canonical" ? "scored" : "catalog-only",
  confidence: options.confidence ?? "provisional",
  aliases: options.aliases ?? [],
  sourceRefs,
  relations: options.relations ?? [],
});

const registryEntry = (
  id: string,
  label: string,
  kind: IdeologyRegistryEntry["kind"],
  summary: string,
  sourceRefs: readonly string[],
  options: Readonly<{
    aliases?: readonly string[];
    relations?: readonly IdeologyRelation[];
  }> = {},
): IdeologyRegistryEntry => ({
  id,
  label,
  kind,
  summary,
  aliases: options.aliases ?? [],
  sourceRefs,
  relations: options.relations ?? [],
});

const liberalism = "liberalism";
const conservatism = "conservatism";
const socialism = "socialism";
const anarchism = "anarchism";
const nationalism = "nationalism";
const republicanism = "republicanism";
const fascism = "fascism";
const ecologism = "ecologism";
const feminism = "feminism";

/**
 * Strict canonical graph. One parent is used only when it is useful for a
 * stable breadcrumb; cross-family and historical relationships live in typed
 * edges or IDEOLOGY_REGISTRY instead of being duplicated as children.
 */
export const IDEOLOGY_NODES: readonly IdeologyNode[] = [
  // Macros: exactly nine fixed roots from the audited input.
  node(liberalism, "Liberalism", "macro", "A plural family organized around justified authority, liberty, rights, equal standing, pluralism, and contestable limits on public power.", ["source-sep-liberalism", "source-oup-liberalism-freeden-steers", "source-cambridge-companion-liberalism", "source-oup-political-ideologies"], { anchorId: "liberalism-family", confidence: "high", aliases: ["Liberalism"] }),
  node(conservatism, "Conservatism", "macro", "A broad family organized around continuity, inherited institutions, order, and prudent change.", ["source-sep-conservatism", "source-oup-conservatism", "source-cambridge-conservatism-traditions"], { anchorId: "conservatism-family", confidence: "high" }),
  node(socialism, "Socialism", "macro", "A plural family defined in contrast with capitalist domination and concerned with social or democratic control of productive resources, equality, solidarity, freedom, democracy, and collective provision.", ["source-sep-socialism", "source-cambridge-politics-socialism", "source-cambridge-socialist-visions", "source-oup-socialism-vsi", "source-oup-political-ideologies"], { anchorId: "socialism-family", confidence: "high" }),
  node(anarchism, "Anarchism", "macro", "A broad family skeptical of imposed hierarchy and interested in voluntary, self-organized forms of social order.", ["source-sep-anarchism", "source-oup-anarchism-ward-introduction", "source-oup-anarchism-federalist-ward", "source-cambridge-history-socialism-anarchism", "source-ostrom"], { anchorId: "anarchism-family", confidence: "high" }),
  node(nationalism, "Nationalism", "macro", "A plural family organized around the political significance of nations, national membership, self-determination, shared identity, and self-government.", ["source-sep-nationalism", "source-oup-nationalism-ere", "source-oup-nationalism-contexts", "source-anderson"], { anchorId: "nationalism-family", confidence: "high" }),
  node(republicanism, "Republicanism", "macro", "A plural family spanning historical civic traditions and contemporary civic or neo-republican theories organized around self-government, civic freedom, and protection from arbitrary power.", ["source-sep-republicanism", "source-oup-republicanism", "source-oup-civic-republicanism", "source-dahl"], { anchorId: "republicanism-family", confidence: "high" }),
  node(fascism, "Fascism", "macro", "A contested family of revolutionary ultranationalist ideologies centered on national rebirth, leadership, mass mobilization, and transformed collective order.", ["source-oup-fascism", "source-oup-political-ideologies"], { confidence: "moderate" }),
  node(ecologism, "Ecologism / Green Ideology", "macro", "A family of ecological political thought concerned with ecological limits, human–nature relations, ecological justice, and the transformation of social organization.", ["source-oup-green-ideology-humphrey", "source-cambridge-green-political-thought-3e", "source-cambridge-ecologism", "source-sep-environmental-ethics"], { anchorId: "ecologism-family", confidence: "high", aliases: ["Ecologism", "Green ideology"] }),
  node(feminism, "Feminism", "macro", "A broad family organized around ending gendered domination and transforming the social structures that reproduce it.", ["source-oup-feminism", "source-oup-feminist-theory", "source-sep-feminist-philosophy", "source-sep-feminist-political"], { anchorId: "feminism-family", confidence: "high" }),

  // Liberalism: four canonical meso nodes.
  node("classical-liberalism", "Classical Liberalism", "meso", "A liberal tradition centered on individual rights, voluntary exchange, and limited public power.", ["source-sep-liberalism", "source-hayek"], { canonicalParentId: liberalism, anchorId: "classical-liberalism", confidence: "high", aliases: ["Classical liberalism"] }),
  node("social-liberalism", "Social Liberalism", "meso", "A liberal tradition combining individual rights with public action to widen practical opportunity.", ["source-sep-liberalism", "source-rawls"], { canonicalParentId: liberalism, anchorId: "social-liberalism", confidence: "high", aliases: ["Social / New Liberalism", "New Liberalism"] }),
  node("libertarianism", "Libertarianism", "meso", "A family of modern political views that gives stringent weight to individual freedom and limits coercion.", ["source-sep-libertarianism", "source-oup-political-ideologies"], { canonicalParentId: liberalism, anchorId: "libertarianism", confidence: "high", aliases: ["modern political libertarianism"] }),
  node("neoliberalism", "Neoliberalism", "meso", "An ideological and intellectual liberal formation associated with market order, competition, and a reworked role for public authority.", ["source-sep-neoliberalism", "source-oup-political-ideologies", "source-oup-ordoliberalism"], { canonicalParentId: liberalism, anchorId: "neoliberalism", confidence: "moderate", aliases: ["neoliberalism in the ideological sense"] }),

  // Conservatism: three meso nodes; New Right is contextual rather than a parent.
  node("moderate-conservatism", "Moderate Conservatism", "meso", "A conservative tradition placing weight on inherited institutions, continuity, prudence, and gradual change.", ["source-oup-conservatism", "source-jost"], { canonicalParentId: conservatism, anchorId: "traditional-conservatism", confidence: "high", aliases: ["Traditional conservatism", "Burkean conservatism"] }),
  node("reactionary-conservatism", "Reactionary Conservatism", "meso", "A conservative current that gives stronger weight to restoration, counter-revolution, or recovered authority than to gradual reform.", ["source-oup-conservatism", "source-oup-pierson-radical-conservatism", "source-frontiers-conservative-revolution"], { canonicalParentId: conservatism, anchorId: "reactionary-conservatism", confidence: "moderate" }),
  node("radical-conservatism", "Radical Conservatism", "meso", "A conservative-revolutionary current seeking decisive renewal of authority, order, or national community.", ["source-oup-conservatism", "source-oup-pierson-radical-conservatism", "source-frontiers-conservative-revolution", "source-oup-fascism"], { canonicalParentId: conservatism, anchorId: "radical-conservatism", confidence: "moderate" }),

  // Socialism: four meso nodes.
  node("marxism", "Marxism", "meso", "A socialist tradition centered on historical materialism, class relations, and critique of capitalist production.", ["source-sep-marx", "source-oup-political-ideologies", "source-sen"], { canonicalParentId: socialism, anchorId: "marxism", confidence: "high", aliases: ["Marxian socialism", "Marxian Socialism"] }),
  node("communism", "Communism", "meso", "A socialist tradition organized around common ownership, class transformation, and forms of post-capitalist social organization.", ["source-oup-communism", "source-oup-socialism-vsi", "source-sep-marx", "source-sen"], { canonicalParentId: socialism, anchorId: "communism", confidence: "high", relations: [relation("overlaps-with", "marxism", "Marxism and Communism overlap historically and conceptually but are not aliases or a single parent-child chain.")] }),
  node("social-democracy", "Social Democracy", "meso", "A socialist tradition combining regulated markets, public provision, parliamentary institutions, and gradual reform.", ["source-oup-social-democracy", "source-esping-andersen", "source-rawls"], { canonicalParentId: socialism, anchorId: "social-democracy", confidence: "high" }),
  node("democratic-socialism", "Democratic Socialism", "meso", "A socialist tradition emphasizing democratic control, social equality, public provision, and structural change through democratic means.", ["source-oup-political-ideologies", "source-sen", "source-rawls"], { canonicalParentId: socialism, anchorId: "democratic-socialism", confidence: "high" }),

  // Anarchism: three meso nodes.
  node("social-anarchism", "Social Anarchism", "meso", "Anarchist traditions emphasizing collective freedom, mutual aid, social equality, and non-hierarchical community.", ["source-sep-anarchism", "source-ostrom", "source-oup-social-ecology"], { canonicalParentId: anarchism, anchorId: "social-anarchism", confidence: "high", aliases: ["Social / Communal Anarchism", "Communal anarchism"] }),
  node("individualist-anarchism", "Individualist Anarchism", "meso", "Anarchist traditions that place individual autonomy and self-determination at the center of their critique of authority.", ["source-sep-anarchism", "source-sep-stirner", "source-sep-libertarianism"], { canonicalParentId: anarchism, anchorId: "individualist-anarchism", confidence: "high" }),
  node("mutualism", "Mutualism", "meso", "An anarchist and cooperative tradition organized around reciprocal association, exchange, and self-governing institutions.", ["source-sep-anarchism", "source-ostrom", "source-wiley-mutualism", "source-oup-socialism-vsi"], { canonicalParentId: anarchism, anchorId: "mutualism", confidence: "moderate" }),

  // Republicanism: historical and contemporary traditions are separate.
  node("historical-republicanism", "Historical Republicanism", "meso", "The historical republican tradition associated with civic virtue, participation, mixed government, rule of law, and resistance to corruption.", ["source-sep-republicanism", "source-oup-republicanism", "source-oup-civic-republicanism"], { canonicalParentId: republicanism, anchorId: "historical-republicanism", confidence: "high", aliases: ["Classical republicanism", "Atlantic republicanism", "Commonwealth republicanism", "Classical / Neo-Roman Republican Tradition"], relations: [relation("historical-tradition-of", republicanism, "This node represents the historical tradition; it is not an alias for contemporary neo-republican theory.")] }),
  node("contemporary-neo-republicanism", "Contemporary Neo-Republicanism", "meso", "A contemporary republican theory emphasizing liberty as non-domination, contestation, and institutional control of arbitrary power.", ["source-sep-republicanism", "source-oup-republicanism", "source-dahl"], { canonicalParentId: republicanism, anchorId: "contemporary-neo-republicanism", confidence: "high", relations: [relation("overlaps-with", "historical-republicanism", "Contemporary neo-republicanism draws on and reinterprets historical republican traditions without being identical to them.")] }),

  // Fascism: national socialism and neo-fascism are meso traditions.
  node("national-socialism", "National Socialism (Nazism)", "meso", "The German National Socialist tradition, distinguished by racial hierarchy, Volksgemeinschaft, Lebensraum, and genocidal politics.", ["source-oup-fascism", "source-oup-national-socialism"], { canonicalParentId: fascism, anchorId: "national-socialism", confidence: "high", aliases: ["National Socialism", "Nazism", "National Socialism / Nazism"] }),
  node("neo-fascism", "Neo-Fascism", "meso", "Post-1945 movements and currents that preserve, revise, adapt, or revive fascist ideological resources.", ["source-oup-fascism", "source-oup-neo-nazism"], { canonicalParentId: fascism, confidence: "high" }),

  // Feminism: two exclusive meso nodes plus parentless hybrid/orthogonal meso nodes.
  node("radical-feminism", "Radical Feminism", "meso", "A feminist tradition treating gendered subordination as a broad structure of dominance rather than only a legal inequality.", ["source-oup-feminism", "source-oup-feminist-theory", "source-sep-feminist-power"], { canonicalParentId: feminism, anchorId: "radical-feminism", confidence: "high" }),
  node("black-feminism", "Black Feminism", "meso", "A feminist tradition analyzing gendered domination together with racialization, class, and other structures of power.", ["source-oup-feminism", "source-oup-feminist-theory", "source-sep-feminist-power", "source-sep-feminist-philosophy"], { canonicalParentId: feminism, anchorId: "black-feminism", confidence: "moderate" }),
  node("liberal-feminism", "Liberal Feminism", "meso", "A feminist tradition organized around autonomy, equal rights, political inclusion, and enabling conditions for freedom.", ["source-oup-feminism", "source-sep-liberal-feminism", "source-sep-liberalism"], { anchorId: "liberal-feminism", confidence: "high", relations: [relation("hybrid-of", liberalism, "Liberal feminism combines feminist commitments with liberal accounts of rights and autonomy."), relation("hybrid-of", feminism, "Feminism is the other constitutive family; this node remains parentless to avoid false exclusive descent.")] }),
  node("socialist-marxist-feminism", "Socialist / Marxist Feminism", "meso", "Feminist traditions connecting gender domination with capitalist production, class relations, and social reproduction.", ["source-oup-feminist-theory", "source-oup-feminism", "source-sep-feminism-class", "source-sep-feminist-power", "source-sep-marx", "source-sen"], { anchorId: "socialist-marxist-feminism", confidence: "high", aliases: ["Socialist-Marxist Feminism"], relations: [relation("hybrid-of", socialism, "This tradition combines feminist and socialist analysis."), relation("hybrid-of", feminism, "Its feminist commitments are constitutive rather than a subordinate branch of one socialist school."), relation("overlaps-with", "marxism", "Marxist and socialist feminist currents overlap without being identical.")] }),
  node("ecofeminism", "Ecofeminism", "meso", "Feminist–ecological traditions connecting gender hierarchy, domination, and ecological degradation.", ["source-oup-feminist-theory", "source-cambridge-ecologism", "source-sep-environmental-ethics", "source-sep-feminist-philosophy"], { anchorId: "ecofeminism", confidence: "moderate", relations: [relation("hybrid-of", feminism, "Ecofeminism is a feminist–ecological synthesis."), relation("hybrid-of", ecologism, "Its ecological commitments are not reducible to generic feminism.")] }),
  node("anarcha-feminism", "Anarcha-Feminism", "meso", "A feminist–anarchist tradition connecting gendered domination with broader critiques of hierarchy and coercive authority.", ["source-sep-anarchism", "source-oup-feminist-theory", "source-oup-feminism"], { anchorId: "anarcha-feminism", confidence: "moderate", relations: [relation("hybrid-of", anarchism, "Anarcha-feminism combines anarchist and feminist critiques."), relation("hybrid-of", feminism, "Its feminist commitments are constitutive rather than an afterthought.")] }),
  node("green-anarchism", "Green Anarchism", "meso", "An anarchist–ecological family connecting anti-hierarchy, ecological limits, and self-organized communities.", ["source-sep-anarchism", "source-cambridge-ecologism", "source-sep-environmental-ethics", "source-oup-social-ecology"], { anchorId: "green-anarchism", confidence: "moderate", relations: [relation("hybrid-of", anarchism, "Green anarchism combines anarchist anti-hierarchy with ecological commitments."), relation("hybrid-of", ecologism, "Its ecological commitments are constitutive rather than a direct parent-child claim.")] }),
  node("ecosocialism", "Ecosocialism", "meso", "A socialist–ecological synthesis connecting ecological protection with ownership, inequality, and collective provision.", ["source-rockstrom", "source-sen", "source-cambridge-ecologism"], { anchorId: "eco-socialism", confidence: "moderate", aliases: ["Eco-socialism"], relations: [relation("hybrid-of", socialism, "Ecosocialism combines socialist and ecological commitments."), relation("hybrid-of", ecologism, "Its ecological commitments are not reducible to generic socialism.")] }),
  node("libertarian-socialism", "Libertarian Socialism", "meso", "A socialist and anti-domination tradition combining equality, collective control, and dispersed power.", ["source-sep-anarchism", "source-ostrom", "source-sen"], { anchorId: "libertarian-socialism", confidence: "high", relations: [relation("hybrid-of", socialism, "Libertarian socialism combines socialist commitments with dispersed power."), relation("hybrid-of", anarchism, "Its anti-hierarchical commitments connect it to anarchist traditions."), relation("overlaps-with", "anarcho-communism", "It overlaps with, but does not subsume, anarcho-communist currents."), relation("overlaps-with", "anarcho-syndicalism", "It overlaps with, but does not subsume, anarcho-syndicalist currents."), relation("overlaps-with", "council-communism", "It overlaps with council-communist commitments to worker self-government."), relation("overlaps-with", "guild-socialism", "It shares self-management concerns with guild socialism.")] }),
  node("liberal-nationalism", "Liberal Nationalism", "meso", "A synthesis joining national self-government with liberal rights, political inclusion, and individual freedom.", ["source-sep-nationalism", "source-sep-liberalism", "source-anderson"], { anchorId: "liberal-nationalism", confidence: "moderate", relations: [relation("hybrid-of", liberalism, "Liberal nationalism combines liberal and national commitments."), relation("hybrid-of", nationalism, "Its national commitments are constitutive rather than an exclusive parent-child claim.")] }),
  node("conservative-nationalism", "Conservative Nationalism", "meso", "A conservative–nationalist synthesis emphasizing national solidarity, inherited continuity, sovereignty, and public authority.", ["source-sep-nationalism", "source-oup-conservatism", "source-ia-national-conservatism", "source-jpi-national-conservatism"], { anchorId: "conservative-nationalism", confidence: "moderate", relations: [relation("hybrid-of", conservatism, "Conservative nationalism combines conservative and national commitments."), relation("hybrid-of", nationalism, "Its national commitments are constitutive rather than an exclusive parent-child claim.")] }),
  node("religious-nationalism", "Religious Nationalism", "meso", "A cross-family formation combining national membership or sovereignty with religious-political traditions.", ["source-oup-religious-nationalism", "source-oup-religious-nationalism-21c", "source-sep-nationalism", "source-oup-political-ideologies"], { anchorId: "religious-nationalism", confidence: "moderate", relations: [relation("hybrid-of", nationalism, "Religious nationalism is a national–religious hybrid."), relation("related-to", conservatism, "Some religious-nationalist projects overlap with conservative traditions without being reducible to them."), relation("related-to", socialism, "Some religious-nationalist projects also develop social or anti-imperial economic programmes.")] }),
  node("christian-democracy", "Christian Democracy", "meso", "An orthogonal ideological tradition combining Christian social thought, democratic institutions, solidarity, and social-market concerns.", ["source-cambridge-christian-democracy", "source-cambridge-christian-democracy-history", "source-oup-political-ideologies", "source-rawls"], { anchorId: "christian-democracy", confidence: "moderate", relations: [relation("related-to", conservatism, "Christian democracy overlaps with some conservative traditions without being a subtype of Conservatism."), relation("related-to", "social-democracy", "Christian democracy can share social-provision concerns with social democracy without being its child.")] }),
  node("populism", "Populism", "meso", "A thin-centred ideology organized around a moralized people–elite distinction whose fuller content depends on a host ideology.", ["source-cambridge-populism", "source-oup-populism", "source-oup-left-populism", "source-oup-right-populism"], { anchorId: "populism", confidence: "high", relations: [relation("hosted-by", liberalism, "Populist claims can be combined with liberal host content."), relation("hosted-by", socialism, "Populist claims can be combined with socialist host content."), relation("hosted-by", nationalism, "Populist claims can be combined with nationalist host content."), relation("hosted-by", conservatism, "Populist claims can be combined with conservative host content.")] }),
  node("islamism", "Islamism", "meso", "A modern religious-political ideology family that seeks to organize political life through an interpretation of Islam, with substantial internal variation.", ["source-cambridge-islamism", "source-oup-islamic-political-ideologies", "source-oup-political-islam", "source-oup-islamism-case-universe"], { anchorId: "islamism", confidence: "moderate", aliases: ["Islamic political ideology", "Political Islam"], relations: [relation("related-to", nationalism, "Some Islamist projects combine religious-political claims with national self-determination."), relation("related-to", conservatism, "Some Islamist projects share social-conservative commitments without being reducible to Conservatism."), relation("related-to", socialism, "Some Islamist projects develop social-justice or anti-capitalist programmes without becoming socialist.")] }),

  // Liberalism micro nodes.
  node("right-libertarianism", "Right-Libertarianism", "micro", "A libertarian branch combining strong self-ownership and property claims with market coordination and a narrow public role.", ["source-sep-libertarianism", "source-nozick"], { canonicalParentId: "libertarianism", anchorId: "right-libertarianism", confidence: "moderate", aliases: ["Right libertarianism", "right libertarian"], relations: [relation("related-to", "minarchism", "Minarchism is a narrower right-libertarian current focused on a minimal protective state."), relation("overlaps-with", "classical-liberalism", "Right-libertarianism overlaps with classical liberalism on rights and markets while taking a more stringent view of coercion and public provision.")] }),
  node("left-libertarianism", "Left-Libertarianism", "micro", "A libertarian current combining strong personal autonomy with concern about equal access, shared resources, or dispersed power.", ["source-sep-libertarianism", "source-sen"], { canonicalParentId: "libertarianism", anchorId: "left-libertarianism", confidence: "moderate", relations: [relation("overlaps-with", "individualist-anarchism", "Some left-libertarian uses overlap with individualist and anarchist currents."), relation("related-to", anarchism, "The broad libertarian tradition has historical and conceptual connections to anarchism.")] }),
  node("minarchism", "Minarchism", "micro", "A narrow-state libertarian tradition focused on core protection, adjudication, and strong personal liberty.", ["source-sep-libertarianism", "source-nozick"], { canonicalParentId: "libertarianism", anchorId: "minarchism", confidence: "moderate", relations: [relation("variant-of", "right-libertarianism", "Minarchism is a narrow-state variant within the right-libertarian space, not a separate rank below it.")] }),
  node("anarcho-capitalism", "Anarcho-Capitalism", "micro", "A contested market-anarchist current that rejects territorial state monopoly in favor of voluntary proprietary, contractual, and polycentric institutions.", ["source-sep-libertarianism", "source-sep-anarchism", "source-cambridge-social-anarchism-anarchocapitalism", "source-cambridge-prevost-anarchocapitalism"], { canonicalParentId: "libertarianism", anchorId: "anarcho-capitalism", confidence: "moderate", relations: [relation("overlaps-with", "individualist-anarchism", "Anarcho-capitalism overlaps with individualist anarchism while remaining contested in its relation to anarchism generally."), relation("overlaps-with", "right-libertarianism", "Anarcho-capitalism shares strong property and market commitments with right-libertarianism but rejects a territorial protective state."), relation("overlaps-with", "minarchism", "Anarcho-capitalism and Minarchism can share rights and market commitments while differing over whether a territorial protective state is legitimate.")] }),
  node("ordoliberalism", "Ordoliberalism", "micro", "A liberal school emphasizing a rules-based competitive order and a state capable of maintaining the conditions for market competition.", ["source-oup-ordoliberalism", "source-oup-political-ideologies"], { canonicalParentId: liberalism, anchorId: "ordoliberalism", confidence: "moderate", relations: [relation("historically-influenced-by", "neoliberalism", "Ordoliberalism has a contested intellectual relationship with neoliberalism; direct Liberalism placement avoids asserting exclusive descent.")] }),

  // Conservative micro nodes.
  node("one-nation-conservatism", "One-Nation Conservatism", "micro", "A historically situated and internally varied conservative tradition joining organic national society, cross-class social cohesion, responsible inherited institutions, and constructive public reform.", ["source-oup-one-nation-conservatism", "source-tandf-walsha-one-nation", "source-policy-press-page-one-nation-welfare", "source-wiley-webb-one-nation-tradition", "source-oup-conservatism", "source-sep-nationalism"], { canonicalParentId: "moderate-conservatism", anchorId: "one-nation-conservatism", confidence: "moderate", relations: [relation("related-to", "social-democracy", "One-Nation Conservatism can overlap with social provision and reform while retaining a conservative account of inherited institutions and national cohesion."), relation("related-to", "national-conservatism", "Both give national community weight, but One-Nation Conservatism is bounded here by cross-class social stewardship and constructive institutional reform rather than membership or sovereignty alone.")] }),
  node("neoconservatism", "Neoconservatism", "micro", "A conservative current associated with order, democracy, foreign-policy activism, and a distinctive relationship to liberal institutions.", ["source-oup-conservatism", "source-oup-political-ideologies"], { canonicalParentId: conservatism, confidence: "moderate", relations: [relation("contextual-cluster-of", "conservative-new-right", "The New Right is retained as a historical/contextual formation, not as this node's exclusive parent."), relation("overlaps-with", "national-conservatism", "Neoconservatism and national conservatism overlap in some contemporary formations but are not aliases.")] }),
  node("paleoconservatism", "Paleoconservatism", "micro", "A conservative current emphasizing national particularity, inherited institutions, restraint, and skepticism toward expansive state or foreign-policy projects.", ["source-oup-conservatism", "source-ia-national-conservatism"], { canonicalParentId: conservatism, confidence: "moderate", relations: [relation("contextual-cluster-of", "conservative-new-right", "The New Right is a historical/contextual formation rather than an exclusive parent."), relation("overlaps-with", "national-conservatism", "Paleoconservatism and national conservatism overlap in some uses but are not aliases.")] }),
  node("national-conservatism", "National Conservatism", "micro", "A conservative-nationalist current emphasizing national solidarity, continuity, sovereignty, and public authority.", ["source-ia-national-conservatism", "source-oup-conservatism"], { canonicalParentId: "conservative-nationalism", anchorId: "national-conservatism", confidence: "moderate", aliases: ["National conservatism"], relations: [relation("overlaps-with", conservatism, "National conservatism overlaps with Conservatism without being a direct child of the macro node."), relation("overlaps-with", nationalism, "National conservatism overlaps with Nationalism without being a direct child of the macro node."), relation("related-to", "paleoconservatism", "The traditions overlap in some contemporary uses but are not aliases."), relation("related-to", "neoconservatism", "The traditions overlap in some contemporary uses but are not aliases."), relation("contextual-cluster-of", "conservative-new-right", "The New Right is retained as historical/contextual context, not a duplicate canonical parent.")] }),

  // Socialist and communist micro nodes.
  node("austromarxism", "Austromarxism", "micro", "A historically specific and internally varied Austrian Marxist and Social Democratic current associated with Habsburg and First Republic contexts, worker-movement unity, democratic socialist institution-building, and personal or non-territorial national autonomy.", ["source-oup-austromarxism", "source-historicalmaterialism-austromarxism", "source-cambridge-red-vienna-austromarxism", "source-oup-benes-workers-nationalism", "source-jstage-renner-national-autonomy", "source-oup-habsburg-national-autonomy", "source-cambridge-national-question-austromarxism", "source-oup-political-ideologies", "source-sen"], { canonicalParentId: "marxism", anchorId: "austromarxism", confidence: "moderate", relations: [relation("overlaps-with", "social-democracy", "Austro-Marxism developed within Austrian Social Democracy but is narrower and more historically specific, joining Marxist theory, worker-movement strategy, and institutional responses to multinational conditions."), relation("related-to", "nationalism", "Its national-autonomy theories address the national question without making nationalism or territorial nation-state formation its sole political principle.")] }),
  node("autonomist-marxism", "Autonomist Marxism", "micro", "A Marxist current emphasizing worker autonomy, social reproduction, and political subjects beyond centralized party command.", ["source-sage-autonomism", "source-antipode-autonomist-marxism", "source-oup-political-ideologies", "source-sen"], { canonicalParentId: "marxism", anchorId: "autonomist-marxism", confidence: "moderate" }),
  node("marxism-leninism", "Marxism-Leninism", "micro", "A historically bounded communist current organized around revolutionary vanguard-party leadership, democratic centralism, state transformation, social or public ownership, planned coordination, and revolutionary internationalism; its historical and national forms vary.", ["source-cambridge-vanguard-party", "source-oup-marxist-democracy", "source-cambridge-democratic-centralism", "source-oup-communism", "source-sep-marx", "source-sen"], { canonicalParentId: "communism", anchorId: "marxism-leninism", confidence: "moderate" }),
  node("trotskyism", "Trotskyism", "micro", "A historically organized and internally varied communist current associated with permanent revolution, internationalism, workers' democracy, and critique of bureaucratic degeneration.", ["source-cambridge-trotskyism", "source-cambridge-trotskyism-permanent-revolution", "source-oup-political-ideologies", "source-oup-communism", "source-sen"], { canonicalParentId: "communism", anchorId: "trotskyism", confidence: "moderate" }),
  node("maoism", "Maoism", "micro", "A historically bounded communist current that adapted Marxism-Leninism to Chinese and other agrarian or colonial conditions through mass-line and practice-centered politics, anti-bureaucratic critique, and revolutionary transformation.", ["source-oup-maoism", "source-oup-maoism-compare", "source-cambridge-maoist-social-history", "source-cambridge-maoism-cultural-revolution", "source-oup-communism", "source-sen"], { canonicalParentId: "communism", anchorId: "maoism", confidence: "moderate", aliases: ["Mao Zedong Thought", "Maoist communism"] }),
  node("council-communism", "Council Communism", "micro", "A communist current emphasizing workers' councils, direct self-government, and opposition to centralized party rule.", ["source-oup-political-ideologies", "source-ostrom", "source-oup-council-democracy", "source-uchicago-council-democracy", "source-oup-communism"], { canonicalParentId: "communism", anchorId: "council-communism", confidence: "moderate", relations: [relation("overlaps-with", "libertarian-socialism", "Council communism overlaps with libertarian-socialist self-management currents.")] }),
  node("guild-socialism", "Guild Socialism", "micro", "A historically situated socialist tradition centered on industrial self-government, functional representation, public or social ownership, and coordination across guild, civic, and territorial associations.", ["source-cambridge-guild-democracy", "source-cambridge-guild-socialism", "source-oup-guild-cooperative", "source-oup-cje-guild-socialism", "source-ostrom"], { canonicalParentId: socialism, anchorId: "guild-socialism", confidence: "moderate", relations: [relation("overlaps-with", "democratic-socialism", "Guild socialism overlaps with democratic socialism without being its exclusive child."), relation("overlaps-with", "council-communism", "Guild socialism shares worker-control concerns with council communism but centers plural guild, civic, and territorial associations rather than councils as the single revolutionary form."), relation("related-to", "libertarian-socialism", "Its self-management concerns connect it to libertarian socialism."), relation("historical-variant-of", socialism, "Guild socialism is retained as a bounded historical socialist current.")] }),

  // Anarchist micro nodes.
  node("anarcho-communism", "Anarcho-Communism", "micro", "A historically varied social-anarchist communist current combining anti-hierarchical organization with common ownership, need-oriented provision, free association, and federated self-management.", ["source-sep-anarchism", "source-cambridge-cahm-anarchist-communism", "source-cambridge-visions-stateless", "source-cambridge-bakunin-social-anarchism", "source-oup-kinna-anarchist-communism", "source-oup-bray-anarchist-communism", "source-ostrom"], { canonicalParentId: "social-anarchism", anchorId: "anarcho-communism", confidence: "moderate", relations: [relation("overlaps-with", "libertarian-socialism", "Anarcho-communism overlaps with libertarian socialism without being an alias."), relation("overlaps-with", "collectivist-anarchism", "Anarcho-communism shares anti-state and collective-control commitments with Collectivist Anarchism while differing historically over distribution, remuneration, and the scope of communist provision.")] }),
  node("collectivist-anarchism", "Collectivist Anarchism", "micro", "A historically bounded social-anarchist current associated especially with Bakunin and the First International, combining collective ownership, labor-linked distribution debates, free federation, and abolition of state rule.", ["source-sep-anarchism", "source-cambridge-cahm-anarchist-communism", "source-cambridge-visions-stateless", "source-cambridge-bakunin-social-anarchism", "source-cambridge-bakunin-statism-anarchy", "source-cambridge-kropotkin-collectivist-wages", "source-oup-anarchism-franks", "source-oup-anarchism-federalist-ward", "source-ostrom"], { canonicalParentId: "social-anarchism", anchorId: "collectivist-anarchism", confidence: "moderate", relations: [relation("overlaps-with", "anarcho-communism", "Collectivist Anarchism shares anti-state collective ownership and federated self-management with Anarcho-Communism but retains a historically distinct labor-contribution and remuneration debate rather than making need-oriented communist distribution constitutive."), relation("overlaps-with", "anarcho-syndicalism", "Both can center worker self-management and anti-state organization, but Anarcho-Syndicalism makes union and direct-action organization more constitutive."), relation("related-to", "libertarian-socialism", "Collectivist Anarchism is historically related to the wider libertarian-socialist field without being its synonym.")] }),
  node("anarcho-syndicalism", "Anarcho-Syndicalism", "micro", "A historically varied social-anarchist current centered on worker organization, direct action, and self-management through unions and federations.", ["source-sep-anarchism", "source-cambridge-history-socialism-anarchism", "source-cambridge-direct-action-syndicalism", "source-cambridge-batalha-syndicalism", "source-ostrom"], { canonicalParentId: "social-anarchism", anchorId: "anarcho-syndicalism", confidence: "moderate", relations: [relation("overlaps-with", "libertarian-socialism", "Anarcho-syndicalism overlaps with libertarian socialism without being an alias."), relation("overlaps-with", "guild-socialism", "Both can center worker self-government, but Anarcho-Syndicalism makes anti-state direct action and union federation more constitutive while Guild Socialism can retain wider plural associational or constitutional arrangements.")] }),
  node("anarcho-pacifism", "Anarcho-Pacifism", "micro", "An anarchist current combining anti-hierarchical politics with serious opposition to war, militarism, and structural violence and a nonviolent or prefigurative transformation route.", ["source-oup-anarcho-pacifism", "source-sage-pacifism-anarchism-landscape", "source-oup-anarchism-world-politics", "source-sep-anarchism"], { canonicalParentId: "social-anarchism", anchorId: "anarcho-pacifism", confidence: "moderate" }),
  node("egoist-anarchism", "Egoist Anarchism", "micro", "A contested individualist-anarchist current associated with Stirnerian self-rule, resistance to imposed identity and compulsory authority, and voluntary association without fixed collective absorption.", ["source-sep-stirner", "source-wiley-stirner-egoism", "source-cambridge-stirner-anarchism", "source-oup-individualist-anarchism", "source-sep-anarchism", "source-sep-libertarianism"], { canonicalParentId: "individualist-anarchism", anchorId: "egoist-anarchism", confidence: "moderate", aliases: ["Egoist anarchism"], relations: [relation("subcurrent-of", "individualist-anarchism", "Egoist Anarchism is retained as a contested Stirner-associated current within the wider individualist-anarchist field."), relation("overlaps-with", "anarcho-capitalism", "Both can reject a compulsory territorial state, but Egoist Anarchism does not make private property, market coordination, or proprietary provision constitutive."), relation("overlaps-with", "collectivist-anarchism", "Both can criticize imposed hierarchy, but Egoist Anarchism centers self-direction and resists compulsory collective identity while Collectivist Anarchism centers common control and solidarity.")] }),
  node("anarcho-primitivism", "Anarcho-Primitivism", "micro", "A contested anti-civilization current within or adjacent to green anarchism, criticizing industrial scale, technological dependence, and civilizational hierarchy while seeking radically decentralized ecological forms of life.", ["source-sep-anarchism", "source-sep-environmental-ethics", "source-tandf-el-ojeili-taylor-anarchoprimitivism", "source-tandf-dunlap-anarchist-civilization", "source-wiley-gordon-anarchism-technology", "source-oup-smith-primitivism-state-nature", "source-ekt-zacharakis-anarcho-primitivism"], { canonicalParentId: "green-anarchism", anchorId: "anarcho-primitivism", confidence: "moderate", relations: [relation("subcurrent-of", "green-anarchism", "Anarcho-Primitivism is retained as a more radical anti-civilization current within or adjacent to the wider Green Anarchist field."), relation("critical-of", "social-ecology", "It shares ecological and anti-hierarchical concerns with Social Ecology while more radically questioning civilization and industrial scale; the traditions are not interchangeable.")] }),
  node("social-ecology", "Social Ecology", "micro", "A historically varied ecological and anti-hierarchical current explaining ecological domination through social hierarchy and advancing democratic municipal or federated self-government with accountable common provision.", ["source-sage-social-ecology-best", "source-sage-democratic-municipalism-shelley", "source-sage-radical-municipalism", "source-frontiers-social-ecology-rojava", "source-sep-environmental-ethics", "source-oup-social-ecology", "source-oup-social-ecology-movements", "source-sep-anarchism"], { canonicalParentId: "green-anarchism", anchorId: "social-ecology", confidence: "moderate", relations: [relation("hybrid-of", anarchism, "Social ecology combines anarchist or communalist anti-hierarchy with ecological commitments."), relation("hybrid-of", ecologism, "Its ecological commitments are constitutive, but it is not duplicated under Ecologism."), relation("overlaps-with", "social-anarchism", "Social ecology overlaps with social anarchism while retaining a distinct ecological theory.")] }),

  // Nationalist micro nodes: overlapping types, not an exhaustive partition.
  node("civic-nationalism", "Civic Nationalism", "micro", "A nationalism that grounds membership primarily in civic institutions, citizenship, and shared political stories.", ["source-sep-nationalism"], { canonicalParentId: nationalism, anchorId: "civic-nationalism", confidence: "moderate", relations: [relation("overlaps-with", "liberal-nationalism", "Civic nationalism overlaps with liberal-nationalist projects in some contexts; the categories are not exhaustive.")] }),
  node("ethnocultural-nationalism", "Ethnocultural Nationalism", "micro", "A contested nationalism that makes shared descent, inherited cultural continuity, language, customs, or ethnocultural membership constitutive of national community or political membership.", ["source-annualreviews-tamir-ethnic-civic", "source-oup-smith-ethnic-nationalism-minorities", "source-oup-smith-culture-community-territory", "source-wiley-piwoni-ethnic-civic-distinction", "source-oup-national-membership-ethnic-model", "source-sep-nationalism"], { canonicalParentId: nationalism, anchorId: "ethnocultural-nationalism", confidence: "moderate", relations: [relation("overlaps-with", "cultural-nationalism", "Ethnocultural and cultural nationalism are overlapping descriptors, not disjoint siblings; the former makes inherited membership constitutive while the latter can center cultural formation without an ancestry rule."), relation("overlaps-with", "civic-nationalism", "Civic and ethnocultural elements can coexist in actual national projects, so this is an analytical boundary rather than a universal binary."), relation("overlaps-with", "religious-nationalism", "Religious and ethnocultural membership can be historically fused, but religious authority or sacred history is not constitutive of every ethnocultural nationalism.")] }),
  node("cultural-nationalism", "Cultural Nationalism", "micro", "A contested nationalist project of forming, preserving, and renewing a national community through language, memory, arts, education, symbols, heritage, and cultural associations, including projects that precede or exceed direct state control; culture is politically consequential but not a fixed essence.", ["source-oup-cultural-nationalism", "source-tandf-spencer-cultural-political-nationalism", "source-oup-hutchinson-memorialization-national-communities", "source-tandf-giudici-grizelj-language-curricula", "source-cje-trohler-national-minded-citizens", "source-sep-nationalism"], { canonicalParentId: nationalism, anchorId: "cultural-nationalism", confidence: "moderate", relations: [relation("overlaps-with", "ethnocultural-nationalism", "Cultural Nationalism can use shared cultural continuity and memory without making ancestry or inherited membership a constitutive political rule."), relation("overlaps-with", "civic-nationalism", "Cultural and civic nationalism are entangled in many historical cases; Cultural Nationalism gives cultural formation political significance without making civic institutions irrelevant."), relation("related-to", "liberal-nationalism", "Cultural Nationalism can combine with rights, pluralism, and liberal self-government without being synonymous with Liberal Nationalism.")] }),
  node("anti-colonial-nationalism", "Anti-Colonial Nationalism", "micro", "A historically varied nationalism organized around resistance to colonial rule and claims to collective self-determination.", ["source-oup-anticolonial-decolonization", "source-cambridge-anticolonial-nationalism", "source-oup-self-determination-decolonization", "source-cambridge-self-rule-colonial-india", "source-oup-decolonization-claims", "source-sep-nationalism"], { canonicalParentId: nationalism, anchorId: "anti-colonial-nationalism", confidence: "moderate", aliases: ["Anti-Colonial / National-Liberation Nationalism", "National-Liberation Nationalism"] }),
  node("integral-nationalism", "Integral Nationalism", "micro", "A nationalism treating the nation as an organic, comprehensive political community with claims over social life.", ["source-sep-nationalism", "source-oup-political-ideologies"], { canonicalParentId: nationalism, confidence: "moderate" }),
  node("arab-nationalism", "Arab Nationalism", "micro", "A historically formed political field centered on wider Arab cultural-linguistic community, collective self-government, cross-border solidarity, and varied territorial or transnational routes.", ["source-oup-arab-nationalism-dawisha", "source-oup-arab-nationalism-emergence", "source-cambridge-arab-nationalism", "source-cambridge-arab-nationalism-frontiers", "source-sep-nationalism"], { canonicalParentId: nationalism, anchorId: "arab-nationalism", confidence: "moderate", aliases: ["Arab / Pan-Arab Nationalism", "Pan-Arabism"], relations: [relation("related-to", "liberal-nationalism", "Arab nationalism has historically combined with varied liberal, socialist, and other host programmes.")] }),
  node("pan-africanism", "Pan-Africanism", "micro", "A transnational political tradition organized around African and diasporic solidarity, liberation, and self-determination.", ["source-oup-political-ideologies", "source-sep-nationalism"], { canonicalParentId: nationalism, anchorId: "pan-africanism", confidence: "moderate" }),
  node("zionism", "Zionism", "micro", "A historically situated and internally varied modern Jewish nationalist tradition joining collective self-determination, political community, cultural or institutional revival, and contested homeland, sovereignty, diaspora, and equal-citizenship questions.", ["source-cambridge-zionism-philosophy", "source-oup-zionism-vsi", "source-cup-boix-jewish-national-identity", "source-yale-shumsky-zionist-political-imagination", "source-oup-mann-zionism-human-rights", "source-sep-nationalism", "source-cambridge-religious-zionism"], { canonicalParentId: nationalism, anchorId: "zionism", confidence: "moderate", relations: [relation("related-to", "religious-zionism", "Religious Zionism remains canonically placed under Religious Nationalism and is related here as a Zionist subvariant rather than duplicated as a child of both nodes."), relation("overlaps-with", "cultural-nationalism", "Zionism can use cultural revival and institutional formation without being reducible to cultural nationalism."), relation("overlaps-with", "ethnocultural-nationalism", "Some Zionist currents treat inherited peoplehood or cultural continuity as constitutive, while Zionism is not exhausted by one ethnocultural membership rule."), relation("overlaps-with", "liberal-nationalism", "Some Zionist currents join Jewish self-determination with equal citizenship, liberal rights, or multinational arrangements without making every Zionist current liberal-nationalist.")] }),
  node("black-nationalism", "Black Nationalism", "micro", "A varied nationalist and liberation tradition centered on Black collective dignity, autonomy, self-directed institutions, and resistance to racial domination.", ["source-sep-nationalism", "source-oup-political-ideologies"], { canonicalParentId: nationalism, anchorId: "black-nationalism", confidence: "moderate" }),
  node("white-nationalism", "White Nationalism", "micro", "A racial-nationalist current asserting a political community organized around white identity; scope and usage must remain explicit.", ["source-sep-nationalism", "source-oup-political-ideologies"], { canonicalParentId: nationalism, confidence: "moderate" }),

  // Republican micro node.
  node("radical-republicanism", "Radical Republicanism", "micro", "A plural radical republican current emphasizing popular sovereignty, freedom as non-domination, equal civic standing, anti-corruption, and contestatory institutional transformation.", ["source-sep-republicanism", "source-oup-republicanism", "source-dahl", "source-oup-radical-republicanism", "source-cambridge-pettit-non-domination", "source-apsr-urbinati-republican-democracy", "source-tandf-thompson-radical-republicanism"], { canonicalParentId: "historical-republicanism", anchorId: "radical-republicanism", confidence: "moderate", relations: [relation("subcurrent-of", "historical-republicanism", "Radical Republicanism is represented as a radical and emancipatory current within the wider historical republican lineage without treating all historical republicanism as radical."), relation("related-to", "contemporary-neo-republicanism", "Both address non-domination and accountable public power, but Radical Republicanism gives stronger weight to popular sovereignty, structural dependence, and transformative contestation."), relation("related-to", "socialism", "Some radical republican scholarship connects republican freedom to capitalist domination and social control, but the traditions are not aliases."), relation("critical-of", "republicanism", "The branch emphasizes the emancipatory and popular potential of republicanism rather than the whole republican family." )] }),

  // Fascist micro nodes. National cases are kept in IDEOLOGY_REGISTRY.
  node("neo-nazism", "Neo-Nazism", "micro", "A postwar current explicitly derived from or attempting to revive National Socialist traditions.", ["source-oup-neo-nazism", "source-specialist-neo-nazi", "source-oup-national-socialism"], { canonicalParentId: "national-socialism", confidence: "moderate", relations: [relation("successor-of", "national-socialism", "Neo-Nazism's primary continuity is with National Socialism."), relation("overlaps-with", "neo-fascism", "Neo-Nazism also participates in the broader postwar neo-fascist field.")] }),
  node("third-positionism", "Third Positionism", "micro", "A postwar fascist current claiming a revolutionary position beyond both capitalism and communism.", ["source-oup-fascism", "source-oup-political-ideologies"], { canonicalParentId: "neo-fascism", confidence: "moderate", aliases: ["Third Position"] }),
  node("falangism", "Falangism", "micro", "A Spanish fascist and national-syndicalist current with distinctive political and religious-national traditions.", ["source-oup-falangism", "source-oup-fascism"], { canonicalParentId: fascism, confidence: "moderate", aliases: ["Falangism / Spanish Fascism"], relations: [relation("related-to", "national-syndicalism", "Falangism has a national-syndicalist relationship; Spanish Fascism remains broader historical context.")] }),
  node("legionary-fascism", "Legionary Fascism", "micro", "A Romanian fascist current with distinctive religious-national, sacrificial, and political-mystical commitments.", ["source-oup-legionary", "source-oup-fascism"], { canonicalParentId: fascism, confidence: "moderate", aliases: ["Romanian Legionary Fascism"], relations: [relation("hybrid-of", "religious-nationalism", "Legionary fascism combines fascist and religious-nationalist commitments."), relation("manifestation-of", fascism, "Romania is retained as historical context rather than as a second ideology node.")] }),
  node("brazilian-integralism", "Brazilian Integralism", "micro", "A Brazilian integralist current with fascist influence and a distinctive Catholic-nationalist programme; classification remains medium confidence.", ["source-oup-brazil-integralism", "source-oup-fascism"], { canonicalParentId: fascism, confidence: "moderate", relations: [relation("hybrid-of", "religious-nationalism", "Brazilian Integralism combines fascist and Catholic/integralist nationalist commitments."), relation("manifestation-of", fascism, "Brazil is retained as historical context rather than as a second ideology node.")] }),

  // Feminist micro nodes.
  node("cultural-feminism", "Cultural Feminism", "micro", "A contested feminist strand emphasizing gendered culture and experience, care, relationship, embodiment, and the political value of practices devalued by dominant institutions without requiring one fixed female essence.", ["source-signs-alcoff-cultural-feminism", "source-oup-alcoff-identity-crisis", "source-cambridge-narayan-cultural-essentialism", "source-oup-kotiswaran-universal-care", "source-oup-feminism-strands", "source-oup-feminist-theory", "source-oup-feminism"], { canonicalParentId: "radical-feminism", anchorId: "cultural-feminism", confidence: "moderate", relations: [relation("overlaps-with", "radical-feminism", "Both can treat gendered power and private/public life as politically constitutive, but Cultural Feminism foregrounds culture, experience, care, and valued difference while Radical Feminism foregrounds patriarchy and structural domination."), relation("overlaps-with", "materialist-feminism", "Both can analyze institutions, embodiment, and devalued social practices, but Materialist Feminism makes labor, production, and material social relations constitutive."), relation("related-to", "lesbian-feminism", "Both can value gendered experience and feminist community, but Lesbian Feminism requires a constitutive critique of compulsory heterosexuality and sexuality institutions."), relation("related-to", "cultural-spiritual-ecofeminism", "Both attend to culture, embodiment, and relational life, but Cultural / Spiritual Ecofeminism requires a linked ecological-gendered analysis.")] }),
  node("lesbian-feminism", "Lesbian Feminism", "micro", "A contested feminist current treating compulsory heterosexuality and gendered sexuality institutions as constitutive sources of women's subordination and linking lesbian autonomy, self-definition, community-building, and alternative institutions to feminist transformation.", ["source-uchicago-rich-compulsory-heterosexuality", "source-wiley-schippers-compulsory-heterosexuality", "source-oup-lee-atchison-lesbian-separatism", "source-oup-hobson-lesbian-feminism-defense", "source-sep-feminism-trans", "source-oup-feminist-theory", "source-oup-feminism-strands"], { canonicalParentId: feminism, anchorId: "lesbian-feminism", confidence: "moderate", relations: [relation("overlaps-with", "radical-feminism", "Lesbian Feminism shares a structural critique of gender and sexuality with Radical Feminism, but it specifically requires compulsory-heterosexuality and lesbian-autonomy or self-definition commitments."), relation("overlaps-with", "cultural-feminism", "Both can center experience, community, and cultural power, but Lesbian Feminism makes compulsory heterosexuality and sexuality institutions constitutive."), relation("related-to", "black-feminism", "Lesbian-feminist organizing and theory include important racial and coalition disputes; Black Feminism has a distinct Black women-centered and interlocking-power boundary.")] }),
  node("womanism", "Womanism", "micro", "A historically varied Black women-centered intellectual, ethical, theological, and political current developed in dialogue with, and sometimes as a critique of, dominant forms of feminism.", ["source-oup-womanist-theology", "source-cambridge-womanism-black-feminism", "source-frontiers-africana-womanism", "source-sage-womanism-survival-wholeness", "source-sep-feminist-philosophy", "source-oup-feminist-theory"], { canonicalParentId: feminism, anchorId: "womanism", confidence: "moderate", relations: [relation("related-to", "black-feminism", "Womanism and Black Feminism are related but not identical, with substantial overlap and internal debate."), relation("critical-of", feminism, "Some womanist formulations criticize dominant or universalizing forms of feminism without rejecting every feminist project."), relation("related-to", "ecofeminism", "Some womanist scholarship develops ecological or spiritual dimensions, but Womanism does not require one ecological doctrine.")] }),
  node("classical-liberal-feminism", "Classical-Liberal Feminism", "micro", "A contested, branch-sensitive liberal feminist current emphasizing equal individual rights, autonomy, noncoercion, constitutional democracy, and skepticism toward coercive equalization.", ["source-sep-liberal-feminism", "source-fpq-baehr-liberal-feminism", "source-sep-libertarianism"], { canonicalParentId: "liberal-feminism", anchorId: "classical-liberal-feminism", confidence: "moderate", aliases: ["Classical-Liberal / Libertarian Feminism", "Libertarian Feminism"], relations: [relation("related-to", "right-libertarianism", "Libertarian feminism is a narrower related current within the classical-liberal family, not an exact alias.")] }),
  node("egalitarian-liberal-feminism", "Egalitarian-Liberal Feminism", "micro", "A liberal feminist family conceiving freedom as personal and political autonomy and emphasizing substantive equality, enabling conditions, democratic inclusion, and accountable public action against gendered institutional barriers.", ["source-sep-liberal-feminism", "source-rawls", "source-oup-feminism", "source-oup-equal-citizenship-feminist-liberalism", "source-oup-mcclain-liberal-feminist-jurisprudence", "source-oup-friedman-autonomy-gender-politics"], { canonicalParentId: "liberal-feminism", anchorId: "egalitarian-liberal-feminism", confidence: "moderate", relations: [relation("overlaps-with", "classical-liberal-feminism", "Both are liberal feminist branches centered on autonomy and equal rights, but Egalitarian-Liberal Feminism gives constitutive weight to enabling conditions and accountable public action rather than primarily noninterference."), relation("related-to", "social-liberalism", "Both may support enabling public institutions, but Egalitarian-Liberal Feminism requires a gendered autonomy and gender-system rationale rather than social liberalism in general."), relation("related-to", "socialist-marxist-feminism", "Both can critique unequal social conditions, but Egalitarian-Liberal Feminism does not require a constitutive production, class, or social-reproduction theory." )] }),
  node("marxist-feminism", "Marxist Feminism", "micro", "A feminist current analyzing gender domination through Marxist accounts of class, production, and capitalist social relations.", ["source-oup-feminist-theory", "source-sen"], { canonicalParentId: "socialist-marxist-feminism", confidence: "moderate" }),
  node("socialist-feminism", "Socialist Feminism", "micro", "A feminist current connecting gender domination with socialist politics, class, institutions, and collective provision.", ["source-oup-feminist-theory", "source-sen"], { canonicalParentId: "socialist-marxist-feminism", confidence: "moderate" }),
  node("materialist-feminism", "Materialist Feminism", "micro", "A plural feminist materialist tradition emphasizing historically specific labor, care, embodiment, institutions, and material social relations in the production of gendered power.", ["source-oup-materialisms-feminist-theory", "source-oup-feminist-theory", "source-sep-feminism-class", "source-sep-feminist-power", "source-sen"], { canonicalParentId: "socialist-marxist-feminism", anchorId: "materialist-feminism", confidence: "moderate" }),
  node("cultural-spiritual-ecofeminism", "Cultural / Spiritual Ecofeminism", "micro", "A plural ecofeminist strand connecting gendered domination and ecological interdependence through cultural, spiritual, symbolic, or relational critique.", ["source-oup-religious-ecofeminism-ruether", "source-oup-ecofeminism-religion", "source-oup-ecofeminism-bibliography", "source-sep-feminist-environmental-philosophy", "source-wiley-ecofeminist-universal-particular", "source-cambridge-feminist-theology-creation", "source-oup-feminist-theory"], { canonicalParentId: "ecofeminism", anchorId: "cultural-spiritual-ecofeminism", confidence: "moderate", relations: [relation("overlaps-with", "cultural-feminism", "Both attend to culture, embodiment, and relational social life, but Cultural / Spiritual Ecofeminism requires the linked ecological-gendered analysis."), relation("overlaps-with", "materialist-socialist-ecofeminism", "The two ecofeminist branches can combine cultural, spiritual, and material registers while emphasizing different mechanisms."), relation("related-to", "ecofeminism", "This is a contested cultural and spiritual strand within the wider plural ecofeminist field.")] }),
  node("materialist-socialist-ecofeminism", "Materialist / Socialist Ecofeminism", "micro", "A plural ecofeminist branch connecting capitalist and patriarchal political economy, paid and unpaid labor, social reproduction, resource control, and ecological degradation, with collective and democratic transformation routes.", ["source-cambridge-oksala-materialist-ecofeminism", "source-oup-materialist-feminist-perspectives-environment", "source-wiley-feminist-political-ecology-sundberg", "source-cambridge-eco-feminist-socialist-just-transition", "source-oup-ecofeminism-bibliography", "source-oup-ecofeminism-religion", "source-oup-feminist-theory", "source-sen"], { canonicalParentId: "ecofeminism", anchorId: "materialist-socialist-ecofeminism", confidence: "moderate", relations: [relation("overlaps-with", "socialist-marxist-feminism", "Materialist and socialist ecofeminist currents overlap with socialist/Marxist feminism through class, labor, and social-reproduction analysis without being identical."), relation("overlaps-with", "cultural-spiritual-ecofeminism", "Both connect feminist and ecological critique, but Materialist / Socialist Ecofeminism requires a material political-economy mechanism rather than primarily cultural or spiritual analysis."), relation("related-to", "ecofeminism", "This is a plural materialist and socialist strand within the wider ecofeminist field.")] }),

  // Religious-nationalist micro nodes.
  node("christian-nationalism", "Christian Nationalism", "micro", "A heterogeneous religious-national political project joining Christian identity or authority claims to national membership and public-institutional power while preserving variation among theological and constitutional routes.", ["source-cambridge-christian-nationalism", "source-cambridge-christian-nationalism-democracy-africa", "source-oup-defining-christian-nationalism", "source-sep-nationalism", "source-oup-political-ideologies"], { canonicalParentId: "religious-nationalism", anchorId: "christian-nationalism", confidence: "moderate", relations: [relation("related-to", "religious-nationalism", "Christian Nationalism specifies Christian political-theological resources within the wider cross-tradition religious-nationalist field."), relation("related-to", nationalism, "The project joins a Christianized account of national community to public authority, but it is not Nationalism in general."), relation("overlaps-with", "christian-democracy", "Both may connect Christian social identity to public institutions, but Christian Democracy is ordinarily pluralist and democratic while Christian Nationalism requires a Christianized national-membership and public-authority project."), relation("overlaps-with", "buddhist-nationalism", "Both join a religious tradition to national political identity, while their theological histories, institutions, and membership narratives differ.")] }),
  node("hindutva", "Hindutva (Hindu Nationalism)", "micro", "A specific Hindu-nationalist ideological formulation; broader Hindu political movements should not be treated as identical.", ["source-oup-hindutva", "source-sep-nationalism"], { canonicalParentId: "religious-nationalism", confidence: "moderate", aliases: ["Hindu Nationalism", "Hindu nationalism"] }),
  node("buddhist-nationalism", "Buddhist Nationalism", "micro", "A variable religious-national political project using Buddhist histories, institutions, symbols, or moral claims to shape national identity, public order, membership, or self-determination.", ["source-oup-buddhist-nationalism", "source-oup-buddhist-nationalism-obo", "source-cambridge-religious-nationalism-south-asia", "source-cambridge-buddhist-nationalism-berkwitz", "source-cambridge-buddhist-activism-walton-jerryson", "source-sep-nationalism", "source-oup-political-ideologies"], { canonicalParentId: "religious-nationalism", anchorId: "buddhist-nationalism", confidence: "moderate", relations: [relation("related-to", "religious-nationalism", "Buddhist Nationalism is a Buddhist-specific branch of the wider religious-nationalist field; jurisdictional and historical forms vary."), relation("related-to", nationalism, "The branch joins Buddhist political identity to national community, but it is not equivalent to Nationalism in general."), relation("overlaps-with", "christian-nationalism", "Both join a religious tradition to national political identity, while their histories, institutions, and doctrinal resources differ.")] }),
  node("religious-zionism", "Religious Zionism", "micro", "A religious-nationalist formulation of Zionism with internally varied theological, territorial, and political commitments.", ["source-cambridge-religious-zionism", "source-sep-nationalism"], { canonicalParentId: "religious-nationalism", confidence: "moderate", relations: [relation("subvariant-of", "zionism", "Religious Zionism is a subvariant of Zionism, represented by relation rather than duplicate placement."), relation("hybrid-of", "zionism", "Its commitments combine Zionist and religious-nationalist traditions.")] }),

  // Populist micro nodes: host relations, not thick ideological descent.
  node("left-wing-populism", "Left-Wing Populism", "micro", "A populist variant whose fuller economic and political content is supplied by left host ideologies.", ["source-cambridge-populism", "source-oup-populism"], { canonicalParentId: "populism", confidence: "moderate", relations: [relation("variant-of", "populism", "The populist core remains thin-centred."), relation("hosted-by", socialism, "Left populist projects may combine the populist core with socialist content."), relation("hosted-by", feminism, "Some left populist projects may combine the populist core with feminist content.")] }),
  node("right-wing-populism", "Right-Wing Populism", "micro", "A populist variant whose fuller national, cultural, and economic content is supplied by right host ideologies.", ["source-cambridge-populism", "source-oup-populism"], { canonicalParentId: "populism", confidence: "moderate", relations: [relation("variant-of", "populism", "The populist core remains thin-centred."), relation("hosted-by", conservatism, "Right populist projects may combine the populist core with conservative content."), relation("hosted-by", nationalism, "Right populist projects may combine the populist core with nationalist content.")] }),

  // Islamist micro nodes.
  node("wasatiyya", "Wasatiyya", "micro", "A contested Islamist current associated with a more inclusive or centrist formulation of political Islam.", ["source-cambridge-wasatiyya", "source-cambridge-islamism"], { canonicalParentId: "islamism", confidence: "moderate", aliases: ["Wasatiyya / Moderate Islamism"], relations: [relation("related-to", "islamism", "Moderation is a context-sensitive descriptor; Wasatiyya is the canonical current label.")] }),
  node("revolutionary-islamism", "Revolutionary Islamism", "micro", "An Islamist current emphasizing revolutionary transformation of political and social order; vanguardism is an associated tendency, not an exact alias.", ["source-cambridge-islamism", "source-oup-political-ideologies"], { canonicalParentId: "islamism", confidence: "moderate", aliases: ["Revolutionary / Vanguardist Islamism", "Vanguardist Islamism"], relations: [relation("related-to", "islamism", "Revolutionary Islamism is a current within the broader Islamist field.")] }),
  node("salafi-jihadism", "Salafi-Jihadism", "micro", "A militant Islamist current combining Salafi doctrinal claims with a jihadist revolutionary project.", ["source-cambridge-islamism", "source-oup-political-ideologies"], { canonicalParentId: "islamism", confidence: "moderate" }),
  node("khomeinism", "Khomeinism", "micro", "A historically specific and internally contested Iranian Shi'i Islamist formation associated with Khomeini's revolutionary interpretation of Islamic governance, jurist guardianship, anti-imperial independence, appeal to the oppressed, and state formation through an Islamic Republic.", ["source-ucp-khomeinism", "source-cambridge-arjomand-khomeini-order", "source-cambridge-namazi-khomeini-sovereign-state", "source-tandf-khomeini-democratic-constitutionalism", "source-oup-ghobadzadeh-governmental-shiism", "source-cambridge-islamism"], { canonicalParentId: "islamism", anchorId: "khomeinism", confidence: "moderate", aliases: ["Khomeini's political ideology"], relations: [relation("variant-of", "islamism", "Khomeinism is treated as a historically specific Islamist current rather than a definition of Islamism as a whole."), relation("related-to", "revolutionary-islamism", "Khomeinism shares revolutionary transformation concerns while having a distinct account of Shi'i jurist guardianship, sovereignty, and state formation."), relation("related-to", "qutbism", "Both are modern Islamist currents, but Khomeinism's Iranian Shi'i jurist-guardianship formation is not interchangeable with Qutbism's divine-sovereignty and jahiliyya framework."), relation("hybrid-of", "populism", "Some scholarship identifies a populist register within Khomeinist mobilization; this is a relation, not canonical ancestry.")] }),
  node("qutbism", "Qutbism", "micro", "A historically situated and internally contested Egyptian Islamist intellectual and political current associated with Sayyid Qutb’s accounts of divine sovereignty, jahiliyya, comprehensive Islamic moral order, disciplined transformative community, and varied revolutionary or reformist reconstitution.", ["source-cambridge-qutb-march", "source-cambridge-qutb-vahdat", "source-oup-toth-qutb", "source-tandf-khatab-qutb-hakimiyya", "source-tandf-faradj-qutb-authority", "source-oup-wagemakers-qutb-legacy", "source-cambridge-islamism"], { canonicalParentId: "islamism", anchorId: "qutbism", confidence: "moderate", aliases: ["Qutbist Islamism"], relations: [relation("variant-of", "islamism", "Qutbism is a historically situated and contested Islamist current, not a synonym for Islamism."), relation("related-to", "revolutionary-islamism", "Qutbism and revolutionary Islamism overlap in transformative orientation while differing across texts, organizations, and historical settings."), relation("related-to", "salafi-jihadism", "Qutb’s concepts were later interpreted in relation to militant currents, but Qutbism and Salafi-Jihadism are not interchangeable."), relation("related-to", "khomeinism", "Both are modern Islamist currents, but Qutbism’s Egyptian Sunni intellectual formation and jahiliyya framework are not interchangeable with Khomeinism’s Iranian Shi’i jurist-guardianship formation.")] }),

  // Broad current anchors that are intentionally contextual rather than
  // additional canonical branches. They keep the existing MVP anchors
  // queryable without inflating the audited 9/33/60 canonical counts.
  node("liberal-conservatism-context", "Liberal Conservatism (broad anchor)", "meso", "A broad anchor combining liberal rights and market coordination with conservative continuity and institutional order.", ["source-sep-liberalism", "source-oup-conservatism"], { anchorId: "liberal-conservatism", placement: "contextual", confidence: "moderate", relations: [relation("hybrid-of", liberalism, "The anchor combines liberal and conservative commitments."), relation("hybrid-of", conservatism, "The anchor combines conservative and liberal commitments.")] }),
  node("market-socialism-context", "Market Socialism (broad anchor)", "meso", "A broad anchor combining social ownership or worker control with market coordination.", ["source-oup-political-ideologies", "source-ostrom"], { anchorId: "market-socialism", placement: "contextual", confidence: "moderate", relations: [relation("related-to", socialism, "The anchor is a broad socialist-market synthesis, not an additional canonical meso branch."), relation("overlaps-with", "democratic-socialism", "Market socialism can overlap with democratic-socialist commitments while differing on coordination and ownership design.")] }),
  node("green-politics", "Green Politics (broad anchor)", "meso", "A broad movement anchor centering ecological limits, democratic participation, and social responsibility.", ["source-cambridge-ecologism", "source-sep-environmental-ethics"], { anchorId: "green-politics", placement: "contextual", confidence: "moderate", relations: [relation("movement-expression", ecologism, "Green politics is treated as a movement expression of the wider Ecologism family.")] }),
  node("green-communitarianism", "Green Communitarianism (broad anchor)", "meso", "A provisional bridge anchor connecting ecological stewardship, local responsibility, and continuity of community practices.", ["source-cambridge-ecologism", "source-ostrom"], { anchorId: "green-communitarianism", placement: "contextual", confidence: "provisional", relations: [relation("related-to", ecologism, "A bridge label with ecological and communitarian content; not a separate canonical macro or meso family.")] }),
  node("anarchism-context", "Anarchism (broad anchor)", "meso", "A broad anchor for anti-hierarchical and self-organized political traditions; internal anarchist diversity requires finer-grained items before a branch label is warranted.", ["source-sep-anarchism", "source-ostrom"], { anchorId: "anarchism", placement: "contextual", confidence: "provisional", relations: [relation("related-to", anarchism, "The broad anchor refers to the Anarchism macro family without asserting an exclusive micro branch.")] }),
];

/**
 * Secondary registry from the audit. These entries remain queryable provenance
 * context but are not canonical ideology nodes or scored neighbors.
 */
export const IDEOLOGY_REGISTRY: readonly IdeologyRegistryEntry[] = [
  registryEntry("conservative-new-right", "Conservative New Right", "contextual-formation", "A heterogeneous historical and political formation associated with several conservative currents; it is not an exclusive parent for Neoconservatism or Paleoconservatism.", ["source-oup-conservatism", "source-ia-national-conservatism"], { aliases: ["New Right", "European New Right"], relations: [relation("contextual-cluster-of", conservatism, "Contextual cluster within the conservative field."), relation("related-to", "neoliberalism", "The formation has historical and intellectual overlap with neoliberal currents.")] }),
  registryEntry("revisionist-bernsteinian-social-democracy", "Revisionist / Bernsteinian Social Democracy", "historical-variant", "A historical doctrinal revision within socialist and social-democratic thought, not a stable contemporary micro subtype.", ["source-oup-social-democracy", "source-oup-political-ideologies"], { aliases: ["Bernsteinian revisionism"], relations: [relation("historical-variant-of", "social-democracy", "Historical variant of Social Democracy.")] }),
  registryEntry("deep-ecology", "Deep Ecology", "associated-tradition", "An ecological philosophy or platform compatible with multiple political programmes; retained outside the strict political-ideology hierarchy.", ["source-sep-environmental-ethics", "source-cambridge-ecologism"], { relations: [relation("related-to", ecologism, "Associated ecological tradition related to Ecologism."), relation("associated-with", "green-anarchism", "Some political ecological currents draw on deep-ecology concepts.")] }),
  registryEntry("bioregionalism", "Bioregionalism", "associated-tradition", "A place-based ecological doctrine with political implications, but mixed planning, cultural, and territorial uses.", ["source-sep-environmental-ethics", "source-cambridge-ecologism"], { relations: [relation("related-to", ecologism, "Associated ecological doctrine related to Ecologism."), relation("related-to", "green-anarchism", "Bioregional ideas overlap with some green-anarchist currents.")] }),
  registryEntry("agrarian-populism", "Agrarian Populism", "historical-variant", "A historically varied rural or movement-specific formation whose content depends on its host context.", ["source-oup-populism", "source-cambridge-populism"], { relations: [relation("historical-variant-of", "populism", "Historical or host-dependent variant of Populism."), relation("hosted-by", nationalism, "Some agrarian populist formations combine populism with nationalist content.")] }),
  registryEntry("civic-republicanism", "Civic Republicanism", "associated-tradition", "A variably used republican label that overlaps with both historical civic traditions and contemporary neo-republican theory; it is retained as a related term rather than an unconditional alias.", ["source-sep-republicanism", "source-oup-republicanism"], { relations: [relation("overlaps-with", "historical-republicanism", "Civic republicanism is used for historical civic traditions in some contexts."), relation("overlaps-with", "contemporary-neo-republicanism", "Civic republicanism is also used for contemporary republican arguments in some contexts.")] }),
  registryEntry("italian-fascism", "Italian Fascism", "historical-manifestation", "The foundational Italian historical manifestation of fascism, retained as context rather than a reusable micro subtype.", ["source-oup-fascism"], { aliases: ["Fascist Italy"], relations: [relation("manifestation-of", fascism, "Historical manifestation of Fascism.")] }),
  registryEntry("british-fascism", "British Fascism", "historical-manifestation", "A national field of British fascist movements and organizations, retained as historical context.", ["source-oup-fascism"], { relations: [relation("manifestation-of", fascism, "Historical manifestation/context of Fascism.")] }),
  registryEntry("french-fascism", "French Fascism", "historical-manifestation", "A contested national field whose relationship to generic fascism varies across scholarship.", ["source-oup-fascism"], { relations: [relation("contested-manifestation-of", fascism, "Contested historical manifestation/context of Fascism.")] }),
  registryEntry("flemish-belgian-fascism", "Flemish / Belgian Fascism", "historical-manifestation", "A national and regional field of fascist movements and cases, retained as historical context.", ["source-oup-fascism"], { aliases: ["Flemish/Belgian Fascism"], relations: [relation("manifestation-of", fascism, "Historical manifestation/context of Fascism.")] }),
  registryEntry("japanese-fascism", "Japanese Fascism", "historical-manifestation", "A contested national case in comparative fascism scholarship, retained as historical context rather than a canonical subtype.", ["source-oup-fascism"], { relations: [relation("contested-manifestation-of", fascism, "Contested historical manifestation/context of Fascism.")] }),
  registryEntry("national-syndicalism", "National-Syndicalism", "associated-tradition", "A related ideological current used as context for some fascist and national-syndicalist formations.", ["source-oup-fascism", "source-oup-political-ideologies"], { aliases: ["National-syndicalist tradition"], relations: [relation("related-to", fascism, "Related tradition used to contextualize bounded fascist currents.")] }),
];

export const ideologyNodeMap = new Map(IDEOLOGY_NODES.map((item) => [item.id, item]));
export const ideologyRegistryMap = new Map(IDEOLOGY_REGISTRY.map((item) => [item.id, item]));
